apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      annotations:
        promethues.io/scrape: "true"
        promethues.io/path: /metrics
        promethues.io/port: "5000"
      labels:
        app: movies
    spec:
      containers:
      - name: movies
        image: viniciuscaol/rotten-potatoes:V1.0.{{tag}}
        ports:
          - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb-service  
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopwd