apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        promethues.io/scrape: "true"
        promethues.io/path: /metrics
        promethues.io/port: "9216"
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          resources: {}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
        - name: mongodbexporter
          image: fabricioveronez/mongo_exporter
          resources: {}
          ports:
            - containerPort: 9216
          env:
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@localhost:27017