version: '3.8'

networks: 
  questao07:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks:
      - questao07

---

