version: '3.8'

networks: 
  rotten-potatoes-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks:
      - rotten-potatoes-network
  
  rotten-potatoes:
    image: viniciuscaol/rotten-potatoes:v1
    container_name: rotten-potatoes
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
    networks:
      - rotten-potatoes-network